plugin: netbox.netbox.nb_inventory
api_endpoint: http://localhost:8000
token: YqzlmfZGBqIGG1TuWxAKlMVClSZDmB9I1bPqzxUd
validate_certs: False
config_context: true
interfaces: True
group_by:
  - device_roles
