--- 
- name: Configuring L3 MTU 9000/ L2 MTU 9014 on Leaf-vJunosRouter0
  hosts: Leaf-vJunosRouter0
  gather_facts: no 
  collections:
    - junipernetworks.junos

  vars:
    jumbo_interfaces:
      - ge-0/0/0
      - ge-0/0/1
      - ge-0/0/2
    l2mtu: 
      9014
    l3mtu:
      9000
  tasks:
    - name: Set L2MTU to 9014 and L3MTU to 9000
      junipernetworks.junos.junos_config: 
        lines:
          - "set interfaces {{ item }} mtu {{ l2mtu }}"
          - "set interfaces {{ item }} unit 0 family inet mtu {{ l3mtu }}"
        comment: "setting l2mtu={{ l2mtu }} and l3mtu={{ l3mtu }} on {{ item }}"
      register: result
      loop: "{{ jumbo_interfaces }}"

    - name: display result 
      debug:
        msg: "updated L2 and L3 MTU"
      when: result.changed

