- name: setting up all nodes
  hosts: kubernetes_nodes
  become: yes
  tasks:
    - name: turning off swap
      command: swapoff -a
      when: ansible_swaptotal_mb > 0

    - name: deleting swap from fstab
      mount:
        name: swap
        fstype: swap
        state: absent

    - name: ensuring that neccessary modules are loaded
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - br_netfilter
        - overlay

    - name: configuring sysctl for containers network
      sysctl:
        name: "{{ item }}"
        state: present
        reload: yes
        value: '1'
        sysctl_set: yes
      loop:
        - net.bridge.bridge-nf-call-iptables
        - net.ipv4.ip_forward
        - net.bridge.bridge-nf-call-ip6tables

- name: setting up the master node
  hosts: kubernetes_master
  become: yes
  tasks:
    - name: fetching k3s installation script
      get_url: 
        url: https://get.k3s.io
        dest: /tmp/install_k3s.sh
        mode: '0755'
    
    - name: Running the installation scirpt
      command: /tmp/install_k3s.sh server --service-cidr=10.6.0.0/16 --cluster-cidr=10.5.0.0/16 --flannel-backend=none
      args:
        creates: /usr/local/bin/k3s

    - name: getting the token for joining nodes
      command: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token_output
      changed_when: false

    - name: outputting the token in the terminal
      set_fact:
        k3s_join_token: "{{ k3s_token_output.stdout }}"
      delegate_to: localhost

- name: Joining the workers
  hosts: kubernetes_workers
  become: yes
  tasks:
    - name: get url for installation
      get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: '0755'

    - name: joining the workers using the token
      command: /tmp/k3s_install.sh agent
      environment:
        K3S_URL: "https://{{ hostvars[groups['kubernetes_master'][0]]['ansible_host'] }}:6443"
        K3S_TOKEN: "{{ hostvars[groups['kubernetes_master'][0]]['k3s_join_token']}}"
      args:
        creates: /usr/local/bin/k3s-agent
