---
- name: Main deployment playbook
  hosts: device_roles_leaf_switch_junos, device_roles_spine_switch_os10
  gather_facts: no 

  tasks:
    - name: merging local context into the dict 
      ansible.builtin.set_fact:
        device_context: "{{ local_context_data | default({}) | combine }}"

    - name: Generating and pushing config for Leaf Switch Junos
      junipernetworks.junos.junos_config:
        src: "./templates/junos/main.j2"
      when: ansible_network_os == 'junipernetworks.junos.junos'

    - name: Generating and pushing config for Spine Switch OS10
      dellemc.os10.os10_config:
        src: "./templates/os10/main.j2"
      when: ansible_network_os == 'dellemc.os10.os10'
