--- 
- name: Test run for os10 spine dell emc s4048-on
  gather_facts: no
  hosts: device_roles_spine_switch_os10

  tasks:
    - name: sh version 
      dellemc.os10.os10_command:
        commands:
          - "show version"
          - "show interface mgmt1/1/1"
      register: shver

    - name: generate config
      dellemc.os10.os10_config:
        src: ./templates/os10/interfaces.j2

    - name: display output
      debug:
        var: shver.stdout_lines
