--- 
- name: Test run for os10 spine dell emc s4048-on
  gather_facts: no
  hosts: device_roles_spine_switch_os10

  tasks:
    - name: generate config
      dellemc.os10.os10_config:
        src: ./templates/os10/interfaces.j2




