router id 45.154.99.209;
log "/var/log/bird.log" all;
define PREFIX = 2a06:9801:1514::/48;
protocol device {
    scan time 10;
  }
protocol kernel {
    ipv6 {
        export all;
        import none;
      };
    persist;
  }
protocol direct {
    ipv6;
    interface "eth*", "lo";
  }
protocol static {
    ipv6;
    route PREFIX blackhole;
    route 2a06:9801:1514:ffff::3/128 via "lo";
  }
function MyPrefix() -> bool {
    return net ~ [2a06:9801:1514::/48+];
  }
filter allowedExport {
    if MyPrefix() then accept;
    reject;
  }
function isBogon() -> bool {
    return net ~ [::/0, fc00::/7+, fe80::/10+, ff00::/8+];
  }
filter allowedFromUpstream {
    if MyPrefix() then reject;
    if isBogon() then reject;
    accept;
  }
protocol bgp ebgptoservpersoas34872 {
    local 2a0c:b640:10::6:209 as 218716;
    neighbor 2a0c:b640:10::6:ffff as 34872;
    ipv6 {
	import limit 500 action block;
        import keep filtered on;
        import filter allowedFromUpstream;
        export filter allowedExport;
      };
  }
