all:
  children:
    juniper_routers:
      hosts:
        Leaf-vJunosRouter0:
          ansible_user: aether
          ansible_connection: netconf
          ansible_port: 830
          ansible_host: 10.1.99.7
          ansible_ssh_private_key_file: /home/yeendrea/.ssh/vJunosRouter_aether_ed25519
          ansible_network_os: junipernetworks.junos.junos
