config setup
    charondebug="ike 2, knl 2, cfg 2"
    uniqueids=no

conn r1-to-r2-policy
    keyexchange=ikev2
    authby=secret
    left=2001:db8:abcd:10::
    leftid=@r1
    leftsubnet=2001:db8:abcd:1111::/64
    right=%any
    rightid=@r2
    rightsubnet=2001:db8:abcd:2222::/64
    ike=aes256-sha256-modp2048
    esp=aes256gcm16
    auto=start
    dpdaction=restart
    closeaction=restart
    ikelifetime = 60s
    lifetime = 30s
    margintime = 15s
