config setup
    charondebug="ike 2, knl 2, cfg 2"
    uniqueids=no

conn r2-to-r1-policy
    keyexchange=ikev2
    authby=secret
    left=2001:db8:abcd:10::1
    leftid=@r2
    leftsubnet=2001:db8:abcd:2222::/64
    right=2001:db8:abcd:10::
    rightid=@r1
    rightsubnet=2001:db8:abcd:1111::/64
    ike=aes256-sha256-modp2048
    esp=aes256-sha256!
    auto=start
    dpdaction=restart
    closeaction=restart
