connections {

    r2-to-r1-policy {
        version      = 2
        local_addrs  = 2001:db8:abcd:10::1
        remote_addrs = 2001:db8:abcd:10::

        proposals    = aes256-sha256-modp2048
        rekey_time   = 60s

        local {
            auth = psk
            id   = r2
        }
        remote {
            auth = psk
            id   = r1
        }

        children {
            r2-to-r1-policy {
                local_ts  = 2001:db8:abcd:2222::/64
                remote_ts = 2001:db8:abcd:1111::/64

                esp_proposals = aes256gcm16

                rekey_time = 15s
                life_time  = 30s

                dpd_action   = restart
                close_action = restart
                start_action = start
            }
        }
    }
}

include swanctl.secrets
