router id 10.99.99.1;
define ASN=65001;
define PREFIX=2001:db8:3333::/48;
log "/var/log/bird.log" all;
protocol device {
    scan time 10;
  }
protocol kernel {
    ipv6 {
        import none;
        export all;
      };
    persist;
  }
protocol direct {
    ipv6;
    interface "lo", "eth*";
  }
protocol static {
    ipv6;
    route PREFIX blackhole;
    route 2001:db8:2222::/48 blackhole;
    route 2001:db8:abcd::1/128 via "lo";
  }
filter isMine {
    if net = PREFIX then accept;
    if net = 2001:db8:2222::/48 then accept;
    if net = 2001:db8:abcd::1/128 then accept;
    reject;
  }
function isBogon() {
    return net ~ [ ::/0, fc00::/7+, fe80::/10+, ff00::/8+ ];
  }
filter allowedFromPeer {
    if isBogon() then reject;
    accept;
  }
protocol bgp ebgptoas {
    local 2001:db8:beef::3 as ASN;
    neighbor 2001:db8:beef::2 as 65000;
    ipv6 {
        export filter isMine;
        import filter allowedFromPeer;
      };
  }
